services:
  personal-website:
    image: personal-website
    container_name: personal-website
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
